name = "basic-cloudflare-worker-rest-api"
type = "javascript"
zone_id = ""
account_id = "YOUR_ACCOUNT_ID"
route = ""
workers_dev = true
compatibility_date = "2021-12-26"

[build]
command = "yarn install && yarn build"
[build.upload]
format = "service-worker"
